php index.php > index.html
php advies.php > advies.html
php begeleiding.php > begeleiding.html
php behandeling.php > behandeling.html
php bekostiging.php > bekostiging.html
php constructie.php > constructie.html
php contact.php > contact.html
php dyslexie.php > dyslexie.html
php gedragsproblemen.php > gedragsproblemen.html
php intake.php > intake.html
php onderzoek.php > onderzoek.html
php rouwverwerking.php > rouwverwerking.html
